2025-06-08 22:14:25,112 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 725716b6df2a2ce3060b1681ae49712313e3156ab2af1b2ee7585b72b69dc7d5
2025-06-08 22:14:25,120 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 92a824aec75ad8302e5f546fd2531c8ff87762bfd72e5050b6120a69c4a99baa
2025-06-08 22:14:25,121 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 7f80d821a920baa16aca54f9d2816af25ef763dac0e91a14b00abc0f87419976
2025-06-08 22:14:25,121 - ERROR - Exception occurred in 62d9b02a491b778cf53dabbd22c6ef5b691db9126261ac878e2c236f26213622: 7b9ea4afe15c0e5fd2b64dc829b6a588b44b3f827e8f48f7af2d96d9ed9c297e
2025-06-08 22:14:25,128 - ERROR - Traceback (most recent call last):
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\database.py", line 72, in add_user
    Uname = helper.symmetric_encrypt(Uname)
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\helper.py", line 30, in symmetric_encrypt
    key = symmetric_get_key()
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\helper.py", line 26, in symmetric_get_key
    with open("secret.key", "rb") as key_file:
         ~~~~^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'secret.key'

2025-06-08 22:14:34,238 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] e332a6b3f0eb0ca62fc4b03f9a461db6a64486e924df8a8c24e2aca26074a2a2
2025-06-08 22:14:34,239 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] db6f6751311f9fdcb04948a67096a5b506522391edde8eaf28496fb140a0cd5a
2025-06-08 22:14:34,239 - ERROR - Exception occurred in 6af677308c6f8a2dd5d727347615b616bf3d95b6759581f27bfab079e7e9e4d2: 7b9ea4afe15c0e5fd2b64dc829b6a588b44b3f827e8f48f7af2d96d9ed9c297e
2025-06-08 22:14:34,241 - ERROR - Traceback (most recent call last):
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\ui.py", line 31, in landing
    sa = auth.auth_super_admin(username, password)
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\authenticator.py", line 12, in auth_super_admin
    username = helper.symmetric_decrypt(username)
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\helper.py", line 39, in symmetric_decrypt
    key = symmetric_get_key()
  File "c:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\helper.py", line 26, in symmetric_get_key
    with open("secret.key", "rb") as key_file:
         ~~~~^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'secret.key'

