2025-06-05 17:45:17,072 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 725716b6df2a2ce3060b1681ae49712313e3156ab2af1b2ee7585b72b69dc7d5
2025-06-05 17:45:17,080 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 92a824aec75ad8302e5f546fd2531c8ff87762bfd72e5050b6120a69c4a99baa
2025-06-05 17:45:17,080 - INFO - [8e66390792b30692e51e2a8c8cc72d201cf528592c72df8accfe2d9459a4eaee] 7f80d821a920baa16aca54f9d2816af25ef763dac0e91a14b00abc0f87419976
2025-06-05 17:45:17,158 - ERROR - Exception occurred in 62d9b02a491b778cf53dabbd22c6ef5b691db9126261ac878e2c236f26213622: 4ca1800417ef883aa00703957a628d7ad46ba2f155fb19c8dde52e28011a866e
2025-06-05 17:45:17,160 - ERROR - Traceback (most recent call last):
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\database.py", line 76, in add_user
    cursor.execute(query, (Fname, Lname, Uname, Pword, Role, Rdate))
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.

