2025-06-12 23:38:38,085 - INFO - User activity logged: Super Admin, Logged in, , Low Risk
2025-06-12 23:38:38,092 - INFO - User activity logged: super_admin, Accessed Super Administrator Dashboard, , Low Risk
2025-06-12 23:38:39,155 - INFO - User activity logged: super_admin, Accessed User Management, , Low Risk
2025-06-12 23:38:50,343 - ERROR - User activity logged: Database, Updating User, Traceback (most recent call last):
  File "C:\Users\Telmo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\database.py", line 150, in update_user
    if Helper.symmetric_decrypt(user[3]) == Helper.symmetric_decrypt(current_username):
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\helper.py", line 75, in symmetric_decrypt
    return engine.decrypt(encrypted).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
, High Risk
