2025-06-13 00:12:40,358 - INFO - User activity logged: Super Admin, Logged in, , Low Risk
2025-06-13 00:12:40,365 - INFO - User activity logged: super_admin, Accessed Super Administrator Dashboard, , Low Risk
2025-06-13 00:12:41,524 - INFO - User activity logged: super_admin, Accessed User Management, , Low Risk
2025-06-13 00:12:43,066 - INFO - User activity logged: super_admin, Viewed users, , Low Risk
2025-06-13 00:12:47,268 - INFO - User activity logged: super_admin, Made a backup, backup_2025-06-13_00-12.zip, Low Risk
2025-06-13 00:12:52,345 - INFO - User activity logged: super_admin, Accessed User Management, , Low Risk
2025-06-13 00:13:12,590 - INFO - User activity logged: super_admin, Added b'gAAAAABoS1D42G7lya6eWIjud1XHJ0JMxJyLTQvnl3NRXEg1D3qFrTHgtrulak8hfX5b1mtTNdXYwSlecmEgGsj_dNG3W3MoWA==', System Administrator, Low Risk
2025-06-13 00:13:15,096 - INFO - User activity logged: super_admin, Viewed users, , Low Risk
2025-06-13 00:13:24,918 - ERROR - User activity logged: super_admin, Restoring a backup, Traceback (most recent call last):
  File "c:\Users\Telmo\OneDrive\Documents\GitHub\FA_SQ_24_25_V1_1\src\models.py", line 311, in restore_system_backup
    zipf.extractall(database.path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\zipfile.py", line 1701, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\zipfile.py", line 1755, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\Telmo\\OneDrive\\Documents\\GitHub\\FA_SQ_24_25_V1_1\\src\\urban_mobility.db\\urban_mobility.db'
, High Risk
