2025-06-10 13:27:38,047 - INFO - User: super_admin / [User Interface] landing page navigation / Low Risk
2025-06-10 13:27:42,799 - INFO - User: super_admin / [User Interface] viewing users / Low Risk
2025-06-10 13:27:42,805 - ERROR - User: super_admin / [during viewing users] Traceback (most recent call last):
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\models.py", line 37, in view_users
    users = database.get_users()
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\database.py", line 122, in get_users
    cursor.execute(query)
    ~~~~~~~~~~~~~~^^^^^^^
sqlite3.OperationalError: no such table: users
 / High Risk
2025-06-10 13:28:09,395 - INFO - User: super_admin / [User Interface] Trying to add a new user / Low Risk
2025-06-10 13:30:43,214 - ERROR - User: super_admin / [during adding a new user] Traceback (most recent call last):
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\models.py", line 100, in add_user
    database.add_new_user(first_name, last_name, username, password, role)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\database.py", line 81, in add_new_user
    valid = self.user_exists(username, password)
  File "C:\Users\Telmo Claro\Documents\Projects\FA_SQ_24_25_V1_1\src\database.py", line 131, in user_exists
    cursor.execute(query)
    ~~~~~~~~~~~~~~^^^^^^^
sqlite3.OperationalError: no such table: users
 / High Risk
